// Every user-visible string lives here (spec §6: English only for now, but
// externalized so Arabic/RTL can be added later without touching components).

export const S = {
  appName: 'Data Maintenance Portal',
  appTagline: 'SAP PM master data change requests',

  nav: {
    home: 'Home',
    myRequests: 'My requests',
    myQueue: 'My queue',
    unassigned: 'Unassigned',
    allRequests: 'All requests',
    newRequest: 'New request',
  },

  home: {
    welcome: (name: string) => `Welcome, ${name}`,
    roleLabel: 'Your roles',
    newRequestCta: 'Create a new request',
    open: 'Open',
    cards: {
      myRequests: 'My requests',
      myDrafts: 'Drafts',
      myOpen: 'Open',
      myQueue: 'Assigned to me',
      unassignedPool: 'Unassigned pool',
      overdue: 'Overdue',
      all: 'All requests',
      completed: 'Completed',
      dashboardSoon: 'Admin dashboard (KPIs and maintainer performance) arrives in Phase 3.',
    },
    errorLoading: 'Could not load your overview.',
  },

  roles: {
    requester: 'Requester',
    maintainer: 'Data Maintainer',
    admin: 'Admin',
    none: 'No DMP role',
  } as Record<string, string>,

  list: {
    title: {
      mine: 'My requests',
      queue: 'My queue',
      unassigned: 'Unassigned requests',
      all: 'All requests',
    },
    searchPlaceholder: 'Search ref, content, requester…',
    statusFilter: 'Status',
    allStatuses: 'All statuses',
    overdueOnly: 'Overdue only',
    columns: {
      ref: 'Ref',
      status: 'Status',
      lines: 'Line items',
      requester: 'Requester',
      assignee: 'Assignee',
      due: 'Due',
    },
    claim: 'Claim',
    empty: 'No requests match.',
    loading: 'Loading requests…',
  },

  status: {
    Draft: 'Draft',
    'Waiting to be started': 'Waiting to be started',
    'In process': 'In process',
    Completed: 'Completed',
    Rejected: 'Rejected',
  } as Record<string, string>,

  sla: {
    overdue: (days: number) => `Overdue by ${days} ${days === 1 ? 'day' : 'days'}`,
    dueIn: (days: number) => `Due in ${days} ${days === 1 ? 'day' : 'days'}`,
    dueToday: 'Due today',
    noDue: 'No due date',
  },

  editor: {
    newTitle: 'New request',
    editTitle: (ref: string) => `Edit draft ${ref}`,
    addLine: 'Add line',
    selectLine: 'Select line',
    selectAll: 'Select all lines',
    duplicate: (n: number) => (n > 0 ? `Duplicate (${n})` : 'Duplicate'),
    deleteLines: (n: number) => (n > 0 ? `Delete (${n})` : 'Delete'),
    action: 'Action',
    lineNo: '#',
    notApplicable: 'n/a',
    saveDraft: 'Save draft',
    submit: 'Submit request',
    saving: 'Saving…',
    submitting: 'Submitting…',
    cancel: 'Cancel',
    tabCount: (n: number) => `(${n})`,
    lineErrorsTitle: 'Fix these before submitting:',
    lineError: (tab: string, n: number, msg: string) => `${tab} line ${n}: ${msg}`,
    noLines: 'No lines yet — click "Add line" to start, or import from an Excel template.',
    requiredHint: "Amber cells are mandatory for that line's action; grey cells don't apply.",
    downloadTemplate: 'Download Excel template',
    importExcel: 'Import from Excel',
    imported: (n: number) => `Imported ${n} ${n === 1 ? 'line' : 'lines'} from Excel.`,
    importNothing: 'No lines were imported.',
    importIssuesTitle: 'Import notes:',
  },

  detail: {
    requester: 'Requester',
    assignee: 'Assignee',
    unassigned: 'Unassigned',
    createdAt: 'Created',
    submittedAt: 'Submitted',
    dueDate: 'Due date',
    slaDays: 'SLA days',
    rejectReason: 'Reject reason',
    linesTitle: 'Line items',
    noLines: 'No line items yet.',
    commentsTitle: 'Comments',
    commentPlaceholder: 'Write a comment…',
    commentAdd: 'Add comment',
    noComments: 'No comments yet.',
    auditTitle: 'Audit trail',
    attachmentsTitle: 'Attachments',
    attachmentsSoon: 'Attachment upload arrives in Phase 3.',
    exportExcel: 'Export to Excel',
    exportSoon: 'Excel export arrives in Phase 3',
    editDraft: 'Edit draft',
    claim: 'Claim this request',
    assign: 'Assign',
    assignTitle: 'Assign to maintainer',
    assignSelect: 'Choose a maintainer',
    reassign: 'Reassign',
    rejectTitle: 'Reject request',
    rejectReasonLabel: 'Reason (required — the requester will see this)',
    rejectConfirm: 'Reject',
    submitBlocked: 'This draft has validation errors — open "Edit draft" to fix them.',
    notFound: 'Request not found.',
    loading: 'Loading request…',
  },

  audit: {
    Created: 'created the request',
    DraftUpdated: 'updated the draft',
    Submitted: 'submitted the request',
    Assigned: 'changed the assignee',
    StatusChanged: 'changed the status',
    Rejected: 'rejected the request',
    Reopened: 'reopened the request as a draft',
    CommentAdded: 'added a comment',
    AttachmentAdded: 'added an attachment',
  } as Record<string, string>,

  roleSwitcher: {
    title: 'Demo role switcher',
    subtitle: 'Mock data only — not part of the real app',
    reset: 'Reset demo data',
  },

  errors: {
    generic: 'Something went wrong.',
    retry: 'Retry',
  },

  notFound: {
    title: 'Page not found',
    goHome: 'Go to home',
  },
} as const
